# Site
repository: stfnh/stfnh
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Stefan Hochwarter
title: Senior Scientist, Joanneum Research HEALTH
email: stefan.hochwarter@joanneum.at
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: stefan-hochwarter
orcid_username: 0000-0003-2652-135X
googlescholar_username: f21vDckAAAAJ
github_username: stfnh

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Stefan and I'm a senior scientist at Joanneum Research HEALTH (Austria). My research interests and expertise are in the field of digital health, in which I have many years of international experience.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Joanneum Research HEALTH, Austria
        link: joanneum.at/health
        sub_title: Senior Scientist
        caption: September 2023 - Present
        description: |
          As a senior scientist at the research group Digital Healthcare Solutions (DHS), I am responsible for acquisition of new research projects and collaboration, scientific monitoring, and project management. The research group is mainly focusing on improving medical treatment processes by developing advanced eHealth and mHealth solutions for both professional users and patients. 

      - layout: left
        title: University of Oslo, Norway
        link: uio.no
        link_text: UiO/DigitalInnovation
        sub_title: Postdoctoral fellow
        caption: 2023 - 2024
        description: |
          Member of the research group Digital Innovation, Department of Informatics.

          Research on Responsible AI (project: AI4Users) in welfare and healthcare services from a human-centered perspective.

      - layout: left
        title: Brandenburg Medical School, Germany
        link: mhb-fontane.de
        sub_title: Research associate
        caption: 2020 - 2022
        description: |
          Member of the research group Digital Health, Center for Health Services Research.

          Research on systems for active participation of patients in their therapy.

      - layout: left
        title: Norwegian University of Science and Technology, Norway
        link: ntnu.edu
        sub_title: PhD Candidate 
        caption: 2018 - 2022
        description: |
          Member of the research group Information Systems and Software Engineering, Department of Computer Science.

          My research focused on the design, implementation and use of welfare technology (eHealth). More details in section *Education* below.

      - layout: left
        title: Centers for Disease Control and Prevention, GA, USA
        link: cdc.gov
        sub_title: Public Health Informatics Fellowship
        caption: 2017 - 2018
        description: |
          The fellowship took place at the National Center for Environmental Health (NCEH), where the National Environmental Public Health Tracking Network (NEPTHN) systematically collects, analyzes and publishes health and environmental data.
          
          My work focussed on providing easy access to these data for the public and health care providers. This was accomplished by creating a visualization library (D3) and integrating environmental public health data with clinical data (SMART on FHIR). 
          
          I also worked with the Southern Nevada Health District to streamline the data collection of the local syringe exchange program for people who inject drugs.

      - layout: left
        title: Self-employed
        sub_title: Consultant, Austria
        caption: 2015 - 2017
        description: |
          Besides other projects:

          Planning and development of data repository for the startup 23 degrees.

          Lead developer of a web-based and community-driven education platform.

          Implementation of a portable documentation system for pediatric nurses.

      - layout: left
        title: humediQ GmbH, Germany
        link: myoncare.com
        sub_title: Software engineer
        caption: 2014 - 2015
        description: |
          Lead implementation of *myoncare*, which is now a digital health platform that offers digital and scalable health support through automated treatment pathways and remote monitoring.

      - layout: left
        title: Karolinska Institute, Sweden
        link: ki.se
        sub_title: Research assistant
        caption: 2013 - 2014
        description: |
          Member of the Department of Global Public Health Sciences.
          
          Work on the EU-funded ARCADE projects (capacity building across Africa and Asia).

          Pilot implementation of a HIV/AIDS clinical decision support systems in three hospitals in Vietnam (field visits).

          Study on electronic health record systems in Vietnam.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Norwegian University of Science and Technology, Norway
        link: ntnu.edu
        sub_title: <mark>PhD</mark> Information Systems
        caption: 2018 - 2023
        description: |
          Thesis title: *The Home as the Centre of Care: A Case Study on Moving Healthcare Services into Homes*

          Supervisors: Eric Monteiro, Babak A. Farshchian, Margunn Aanestad

          Disputation date: January 12, 2023

      - layout: left
        title: Karolinska Institute, Sweden
        link: ki.se
        sub_title: <mark>MSc</mark> Health Informatics
        caption: 2011 - 2013
        description: |
          Thesis title: *Innovational educational technologies to strengthen health research in Asia: Study of the performance and adaptability of a Minisip ARCADE implementation in low- and middle-income countries*

          Supervisor: Nabil Zary

      - layout: left
        title: National University of Singapore
        link: nus.edu.sg
        sub_title: Research exchange
        caption: Spring 2013
        description: |
          Evaluation and implementation study with partner universities in India and China.

      - layout: left
        title: Linnaeus University, Sweden 
        link: lnu.se
        sub_title: <mark>BSc</mark> Computer Science
        caption: 2009 - 2010
        description: |
           Thesis title: *colorXtractor - a technical aid for people with color blindness*

           Supervisor: Tobias Andersson-Gidlund

           (Erasmus program)

      - layout: left
        title: Vienna University of Technology, Austria 
        link: tuwien.at
        caption: 2007 - 2009
        description: |
           Study of the bachelor program *Medical Informatics* (completed during Erasmus stay in Sweden)

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
